//
// Created by spaceeye on 01.11.22.
//

#ifndef ANOTHERPROGRAMMINGLANGUAGE_MATHEXPRESSIONPARSER_H
#define ANOTHERPROGRAMMINGLANGUAGE_MATHEXPRESSIONPARSER_H


class MathExpressionParser {

};


#endif //ANOTHERPROGRAMMINGLANGUAGE_MATHEXPRESSIONPARSER_H
