//
// Created by spaceeye on 29.10.22.
//

#ifndef ANOTHERPROGRAMMINGLANGUAGE_VARIABLETYPE_H
#define ANOTHERPROGRAMMINGLANGUAGE_VARIABLETYPE_H

enum class VariableType {
    VOID,
    //ONLY FOR 4 BYTE TYPES
    B_ANY,
    INT,
    UINT,
    FLOAT,
    ARRAY,
    STRING
};

#endif //ANOTHERPROGRAMMINGLANGUAGE_VARIABLETYPE_H
