//
// Created by spaceeye on 25.10.22.
//

#ifndef ANOTHERPROGRAMMINGLANGUAGE_BYTECODE_H
#define ANOTHERPROGRAMMINGLANGUAGE_BYTECODE_H

enum class ByteCode {
    VOID,
};

#endif //ANOTHERPROGRAMMINGLANGUAGE_BYTECODE_H
